### ISSUE TITLE
Running Inference on another dataset

### ISSUE THREAD

**Issue by ansariyusuf** [HuayuLiArizona/Score-based-ECG-Denoising#1]
Hi,

Thank you for this wonderful work! I would like to use your model to denoise publicly available datasets (say, PTB-XL). Is there a script to quickly run the inference using the models you trained from your end?

**Comment by HuayuLiArizona** [comment]
Updated, please check _quickly_run_template.py_.

**Comment by ansariyusuf** [comment]
Thank you very much for posting the script!

I have a few follow-up queries regarding the inference on the external dataset.
1. I plan to use some ECGs from PTB-XL on your model. The sampling rate of ECGs is 100Hz or 500Hz. Will this be an issue for the trained model? Additionally, The duration of the ECG is 10 sec. Will the model be able to denoise the entire signal (1000 samples or 5000 samples) in one go?
2. It will be very helpful if you share the conda environment yaml file in the configs folder or the dependencies for this project. It will help us get this repo running quickly.


Thanks for all the help!

**Comment by HuayuLiArizona** [comment]
1. I have no idea whether the pre-trained model works for your data. My model is trained on 250 Hz. The input size doesn't matter.
2. There are no specific environmental requirements. Just use the newest version of PyTorch, and you may need to install wfdb (by "pip install wfdb").

**Comment by ansariyusuf** [comment]
Thank you for the response. 

I went through the code and base briefly and the paper. I have observed that the focus is primarily on the BW noise. I am curious to know if you have run any experiments to denoise EM and MA noise from NSTDB?

**Comment by HuayuLiArizona** [comment]
Yes, the results on the EM and MA noise are close to BW. However, I haven't saved the pre-trained models on my permanent storage. You can run those by modifying the preprocessing script.
