### ISSUE TITLE
(NSTDB) numpy.AxisError: axis 2 is out of bounds for array of dimension 2

### ISSUE THREAD

**Issue by Basheer88** [HuayuLiArizona/Score-based-ECG-Denoising#3]
MIT QT database saved as pickle file
Namespace(config='base.yaml', device='cuda:0', n_type=1)
folder: ./check_points/noise_type_1/
Getting the Data ready ...

MIT QT database saved as pickle file
fs 360
sig_len 650000
n_sig 2
base_date None
base_time None
units ['mV', 'mV']
sig_name ['noise1', 'noise2']
comments []
fs 360
sig_len 650000
n_sig 2
base_date None
base_time None
units ['mV', 'mV']
sig_name ['noise1', 'noise2']
comments []
fs 360
sig_len 650000
n_sig 2
base_date None
base_time None
units ['mV', 'mV']
sig_name ['noise1', 'noise2']
comments []

MIT BIH data noise stress test database (NSTDB) saved as pickle
rnd_test shape: (0,)
Traceback (most recent call last):
  File "D:\Score-based-ECG-Denoising-main\main_exp.py", line 36, in <module>
    [X_train, y_train, X_test, y_test] = Data_Preparation(args.n_type)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Score-based-ECG-Denoising-main\Data_Preparation\data_preparation.py", line 182, in Data_Preparation
    X_test = np.expand_dims(X_test, axis=2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in expand_dims
  File "C:\Users\BASHEER\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\shape_base.py", line 597, in expand_dims
    axis = normalize_axis_tuple(axis, out_ndim)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BASHEER\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\numeric.py", line 1398, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BASHEER\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\numeric.py", line 1398, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.AxisError: axis 2 is out of bounds for array of dimension 2

**Comment by HuayuLiArizona** [comment]
Can you check the shape of X_test?
Like:
print(X_test.shape)
X_test = np.expand_dims(X_test, axis=2)

**Comment by Basheer88** [comment]
it shows 
(0,)

You mentioned that the data preprocessing is directly taken from [DeepFilter](https://www.sciencedirect.com/science/article/pii/S1746809421005899). So I run it too and give same error. am not sure but maybe the dataset slightly changed or reading files give return null. uploading the data folder might fix this issue

**Comment by HuayuLiArizona** [comment]
Can you check whether you properly put the dataset or set the proper path for the test sampels?
Try both paths of the test samples to see which one works:
'''
    test_set = ['qt-database-1.0.0/sel123',  # Record from MIT-BIH Arrhythmia Database
                'qt-database-1.0.0/sel233',  # Record from MIT-BIH Arrhythmia Database

                'qt-database-1.0.0/sel302',  # Record from MIT-BIH ST Change Database
                'qt-database-1.0.0/sel307',  # Record from MIT-BIH ST Change Database

                'qt-database-1.0.0/sel820',  # Record from MIT-BIH Supraventricular Arrhythmia Database
                'qt-database-1.0.0/sel853',  # Record from MIT-BIH Supraventricular Arrhythmia Database

                'qt-database-1.0.0/sel16420',  # Record from MIT-BIH Normal Sinus Rhythm Database
                'qt-database-1.0.0/sel16795',  # Record from MIT-BIH Normal Sinus Rhythm Database

                'qt-database-1.0.0/sele0106',  # Record from European ST-T Database
                'qt-database-1.0.0/sele0121',  # Record from European ST-T Database

                'qt-database-1.0.0/sel32',  # Record from ``sudden death'' patients from BIH
                'qt-database-1.0.0/sel49',  # Record from ``sudden death'' patients from BIH

                'qt-database-1.0.0/sel14046',  # Record from MIT-BIH Long-Term ECG Database
                'qt-database-1.0.0/sel15814',  # Record from MIT-BIH Long-Term ECG Database
                ]
    '''
    test_set = ['sel123',  # Record from MIT-BIH Arrhythmia Database
                'sel233',  # Record from MIT-BIH Arrhythmia Database

                'sel302',  # Record from MIT-BIH ST Change Database
                'sel307',  # Record from MIT-BIH ST Change Database

                'sel820',  # Record from MIT-BIH Supraventricular Arrhythmia Database
                'sel853',  # Record from MIT-BIH Supraventricular Arrhythmia Database

                'sel16420',  # Record from MIT-BIH Normal Sinus Rhythm Database
                'sel16795',  # Record from MIT-BIH Normal Sinus Rhythm Database

                'sele0106',  # Record from European ST-T Database
                'sele0121',  # Record from European ST-T Database

                'sel32',  # Record from ``sudden death'' patients from BIH
                'sel49',  # Record from ``sudden death'' patients from BIH

                'sel14046',  # Record from MIT-BIH Long-Term ECG Database
                'sel15814',  # Record from MIT-BIH Long-Term ECG Database
                ]

**Comment by Basheer88** [comment]
Both path return 
(0,)

Files already there

**Comment by Basheer88** [comment]
Both paths return (0,).

After using the first test path and conducting several checks, I found that there is an additional \ and most likely because I am using a Windows environment.
